### ISSUE TITLE
Compress Math Section

### ISSUE THREAD

**Issue by tomekmarchi** [tomekmarchi/Acid#2]
The math section is far to large and requires a simpler re-write. This will eliminate a lot of redundant code.

**Comment by woollybogger** [comment]
Is [this](https://github.com/tomekmarchi/Acid/blob/master/build/modules/number/modules/math.js) the math section you're referring to?

**Comment by tomekmarchi** [comment]
LOL, that it is.

**Comment by tomekmarchi** [comment]
https://github.com/tomekmarchi/Acid/blob/master/build/modules/number/modules/math.js Thank you Nate for the advice here is the most recent update of that file. Much has been removed as you can tell. Will be enacting all your recommendations!

**Comment by woollybogger** [comment]
Looks great! That's exactly what I had in mind for what that section should look like :+1:
